from moderation.tests.unit.register import *
from moderation.tests.unit.managers import *
from moderation.tests.unit.models import *
from moderation.tests.unit.utils import *
from moderation.tests.unit.admin import *
from moderation.tests.unit.diff import *
from moderation.tests.unit.forms import *
from moderation.tests.unit.moderator import *
from moderation.tests.regression import *
from moderation.tests.acceptance.exclude import *
from moderation.tests.acceptance.auto_discover import *
