from moderation.tests.test_register import *
from moderation.tests.test_menagers import *
from moderation.tests.test_models import *
from moderation.tests.test_utils_functions import *
from moderation.tests.test_admin import *
from moderation.tests.test_diff import *
from moderation.tests.test_forms import *
from moderation.tests.test_generic_moderator import *
from moderation.tests.regresion_tests import *
