# Generated by Django 2.2.14 on 2021-10-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0005_auto_20190412_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderatedobject',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Rejected'), (1, 'Approved'), (2, 'Pending'), (3, 'Visible until rejected')], default=2, editable=False),
        ),
    ]
